const FORM_CONFIG={  
  "25KV Interrupter":[
    {"sr":"A","label":"Name of the ","type":"dropdown","options":["TSS","SS","SSP"],"required":true},
{sr:"1",label:"Rly. Identification No.",type:"text",required:true},
{sr:"2",label:"Make",type:"text",required:true},
{sr:"3",label:"Maker Sl.No",type:"text",required:true},
{sr:"4",label:"Manufacture's Year",type:"text",required:true},
{sr:"5",label:"External condition (check porcelain carefully)",type:"text",required:true},
{sr:"6",label:"Insulation Resistance (with 2.5/5kv Megger) for ALIND,BHEL as per TI/MI/0054  / OEM",type:"group",required:true,fields:[{sr:"6.1",label:"a) Top to bottom:",type:"number",placeholder:"≥ 5000 MΩ",min:5000,required:true},{sr:"6.2",label:"b) Top to earth:",type:"number",placeholder:"≥ 5000 MΩ",min:5000,required:true},{sr:"6.3",label:"c) Bottom to earth:",type:"number",placeholder:"≥ 5000 MΩ",min:5000,required:true},{sr:"6.4",label:"d)Top to Bottom to Earth (CB Close)",type:"number",placeholder:"≥ 5000 MΩ",min:5000,required:true}]},
{sr:"7",label:"Insulation Resistance (with 2.5/ 5kv Megger) as per OEM (Megawin) Manual",type:"group",required:true,fields:[{sr:"7.1",label:"a) Top to bottom:",type:"number",placeholder:"≥ 300 MΩ",min:300,required:true},{sr:"7.2",label:"b) Top to earth:",type:"number",placeholder:"≥ 300 MΩ",min:300,required:true},{sr:"7.3",label:"c) Bottom to earth:",type:"number",placeholder:"≥ 300 MΩ",min:300,required:true},{sr:"7.4",label:"d)Top to Bottom to Earth (CB Close)",type:"number",placeholder:"≥ 300 MΩ",min:300,required:true}]},
{sr:"8",label:"Insulation Resistance (with 2.5/5kv Megger) as per OEM (Vans) Manual",type:"group",required:true,fields:[{sr:"8.1",label:"a) Top to bottom:",type:"number",placeholder:"≥ 100 MΩ",min:100,required:true},{sr:"8.2",label:"b) Top to earth:",type:"number",placeholder:"≥ 100 MΩ",min:100,required:true},{sr:"8.3",label:"c) Bottom to earth:",type:"number",placeholder:"≥ 100 MΩ",min:100,required:true},{sr:"8.4",label:"d)Top to Bottom to Earth (CB Close)",type:"number",placeholder:"≥ 100 MΩ",min:100,required:true}]},
{sr:"9",label:"Insulation Resistance/Resistance (with 500V Megger)",type:"group",required:true,fields:[{sr:"9.1",label:"a)Spring charging motor with earth",type:"number",placeholder:"≥ 2 MΩ",min:2,required:true},{sr:"9.2",label:"b)Closing coil resistance",type:"number",placeholder:"≥ 2 MΩ",min:2,required:true},{sr:"9.3",label:"c)Trip coil resistance",type:"number",placeholder:"≥ 2 MΩ",min:2,required:true},{sr:"9.4",label:"d)Spring charging  Time Of motor",type:"number",placeholder:"≤ 12 Sec.",max:12,required:true}]},
{sr:"10",label:"Contact resistance as per TI/MI/0054",type:"group",required:true,fields:[{sr:"10.1",label:"ALIND",type:"number",placeholder:"≤ 50 µΩ",max:50,required:true},{sr:"10.2",label:"Megawin",type:"number",placeholder:"≤ 100 µΩ",max:100,required:true},{sr:"10.3",label:"BHEL",type:"number",placeholder:"≤ 80 µΩ",max:80,required:true}]},
{sr:"11",label:"Operating time as per TI/MI/0054",type:"group",required:true,fields:[{sr:"11.1",label:"Alind Make",type:"text",required:true}]},
{sr:"12",label:"a) Closing",type:"number",placeholder:"≤ 120 ms",max:120,required:true},
{sr:"13",label:"b) Opening",type:"number",placeholder:"≤ 90 ms",max:90,required:true},
{sr:"14",label:"VANS Make as per OEM",type:"group",required:true,fields:[{sr:"14.1",label:"a) Closing",type:"number",placeholder:"≤ 80 ms",max:80,required:true},{sr:"14.2",label:"b) Opening",type:"number",placeholder:"≤ 65 ms",max:65,required:true}]},
{sr:"15",label:"Megawin Make",type:"group",required:true,fields:[{sr:"15.1",label:"a) Closing",type:"number",placeholder:"≤ 120 ms",max:120,required:true},{sr:"15.2",label:"b) Opening",type:"number",placeholder:"≤ 90 m",max:90,required:true}]},
{sr:"16",label:"Key No.",type:"group",required:true,fields:[{sr:"16.1",label:"Wipe (W1-W2) for Alind",type:"text",placeholder:"8+1/-0",required:true},{sr:"16.2",label:"W1",type:"text",required:true},{sr:"16.3",label:"W2",type:"text",required:true},{sr:"16.4",label:"Travel (T1-T2) for Alind",type:"text",placeholder:"22±1",required:true},{sr:"16.5",label:"T1",type:"text",required:true},{sr:"16.6",label:"T2",type:"text",required:true}]},
{sr:"17",label:"Local/Remote operation",type:"text",required:true},
{sr:"18",label:"Duplicate earth and earth continuity",type:"group",required:true,fields:[{sr:"18.1",label:"Terminal connection (check fortightness)",type:"textarea",placeholder:"OK / Not OK",multiline:true,required:true}]},
{sr:"19",label:"Check for",type:"group",required:true,fields:[{sr:"19.1",label:"Mechanical tripping & closing",type:"text",required:true},{sr:"19.2",label:"Heater circuit",type:"text",required:true},{sr:"19.3",label:"Counter",type:"text",required:true}]},
{sr:"20",label:"Megger Used",type:"group",required:true,fields:[{sr:"20.1",label:"a) Make",type:"text",required:true},{sr:"20.2",label:"b) Serial No.",type:"text",required:true}]}
],
" 42 KV LA":[
  {"sr":"A","label":"Name of the ","type":"dropdown","options":["TSS","SS","SSP"],"required":true},
{sr:"1",label:"Rly Identification No.",type:"text",required:true},
{sr:"2",label:"Make",type:"text",required:true},
{sr:"3",label:"Type",type:"text",required:true},
{sr:"4",label:"Maker Sl.No",type:"text",required:true},
{sr:"5",label:"Manfacture's Year",type:"text",required:true},
{sr:"6",label:"Rating",type:"text",required:true},
{sr:"7",label:"External condition",type:"text",required:true},
{sr:"8",label:"Duplicate earth and earth continuity",type:"text",required:true},
{sr:"9",label:"Terminal connectors (check for tightness and general condition)",type:"textarea",placeholder:"OK / Not OK",multiline:true,required:true},
{sr:"10",label:"Insulation resistance with 5kv Insulation Tester (as per TI/MI/0041 )",type:"group",required:true,fields:[{sr:"10.1",label:"Top to Earth",type:"number",placeholder:"≥ 1 GΩ",min:1,required:true},{sr:"10.2",label:"Top to bottom",type:"number",placeholder:"≥ 1 GΩ",min:1,required:true}]},
{sr:"11",label:"Base insulator",type:"text",required:true},
{sr:"12",label:"Check Disconnector assembly",type:"text",required:true},
{sr:"13",label:"Size of flexible cable for disconnector",type:"text",placeholder:"35sqmm",required:true},
{sr:"14",label:"Check Surge monitor",type:"text",required:true},
{sr:"15",label:"Resistive Leakage current",type:"number",placeholder:"≤ 500 micro Amp",max:500,required:true},
{sr:"16",label:"Surge monitor serial no",type:"text",required:true},
{sr:"17",label:"Surge monitor counter reading",type:"text",required:true}
],

"25KV PT ":[
{"sr":"A","label":"Name of the ","type":"dropdown","options":["TSS","SS","SSP"],"required":true},
{sr:"2",label:"Rly Identification No.",type:"text",required:true},
{sr:"2",label:"Make",type:"text",required:true},
{sr:"3",label:"Maker Sl.No",type:"text",required:true},
{sr:"4",label:"Manufacter's Year",type:"text",required:true},
{sr:"5",label:"Insulator( Check Condition)",type:"text",required:true},
{sr:"6",label:"Voltage Ratio",type:"text",required:true},
{sr:"7",label:"VA Rating",type:"text",required:true},
{sr:"8",label:"Insulation resistance between(as per OEM)",type:"group",required:true,fields:[{sr:"8.1",label:"a) Pri to earth with 2.5kv Insulation Tester",type:"number",placeholder:"≥ 200 MΩ",min:200,required:true},{sr:"8.2",label:"b) Pri to sec with 2.5kv Insulation Tester",type:"number",placeholder:"≥ 200 MΩ",min:200,required:true},{sr:"8.3",label:"c) Sec to earth with 500v Insulation Tester",type:"number",placeholder:"≥ 2 MΩ",min:2,required:true}]},
{sr:"9",label:"Secondary Fuse Rating",type:"text",placeholder:"amp",required:true},
{sr:"10",label:"Secondary continuity",type:"text",required:true},
{sr:"11",label:"Duplicate earth and earth continuity",type:"text",required:true},
{sr:"12",label:"Terminal connector (check for",type:"textarea",placeholder:"OK / Not OK",multiline:true,required:true},
{sr:"13",label:"tightness and general condition)",type:"text",required:true},
{sr:"14",label:"Ratio test",type:"multi",placeholder:"Applied Voltage in Primary",count:2,labels:["Pri Voltage","Main Voltage"],unit: "MΩ",min: 10,max: 20,required:true}
],
" 42 KV LA":[
{"sr":"A","label":"Name of the ","type":"dropdown","options":["TSS","SS","SSP"],"required":true},
{sr:"2",label:"Rly Identification No.",type:"text",required:true},
{sr:"3",label:"Make",type:"text",required:true},
{sr:"4",label:"Type",type:"text",required:true},
{sr:"4",label:"Maker Sl.No",type:"text",required:true},
{sr:"5",label:"Manfacture's Year",type:"text",required:true},
{sr:"6",label:"Rating",type:"text",required:true},
{sr:"7",label:"External condition",type:"text",required:true},
{sr:"8",label:"Duplicate earth and earth continuity",type:"text",required:true},
{sr:"9",label:"Terminal connectors (check for tightness and general condition)",type:"textarea",placeholder:"OK / Not OK",multiline:true,required:true},
{sr:"10",label:"Insulation resistance with 5kv Insulation Tester (as per TI/MI/0041 )",type:"group",required:true,fields:[{sr:"1.1",label:"Top to Earth",type:"number",placeholder:"≥ 1 GΩ",min:1,required:true},{sr:"1.2",label:"Top to bottom",type:"number",placeholder:"≥ 1 GΩ",min:1,required:true}]},
{sr:"11",label:"Base insulator",type:"text",required:true},
{sr:"12",label:"Check Disconnector assembly",type:"text",required:true},
{sr:"13",label:"Size of flexible cable for disconnector",type:"text",placeholder:"35sqmm",required:true},
{sr:"14",label:"Check Surge monitor",type:"text",required:true},
{sr:"15",label:"Resistive Leakage current",type:"number",placeholder:"≤ 500 micro Amp",max:500,required:true},
{sr:"16",label:"Surge monitor serial no",type:"text",required:true},
{sr:"17",label:"Surge monitor counter reading",type:"text",required:true}
],
" 25KV VCB":[
{"sr":"A","label":"Name of the ","type":"dropdown","options":["TSS","SS","SSP"],"required":true},
{sr:"1",label:"Rly Identification No.",type:"text",required:true},
{sr:"2",label:"Make",type:"text",required:true},
{sr:"3",label:"Maker Sl.No",type:"text",required:true},
{sr:"4",label:"Manufacture's Year",type:"text",required:true},
{sr:"5",label:"External condition (check porcelain carefully)",type:"text",required:true},
{sr:"6",label:"Insulation Resistance (with 2.5/5kv Megger) for ALIND,BHEL as per TI/MI/0054  / OEM",type:"group",required:true,fields:[{sr:"6.1",label:"a) Top to bottom:",type:"number",placeholder:"≥ 5000 MΩ",min:5000,required:true},{sr:"6.2",label:"b) Top to earth:",type:"number",placeholder:"≥ 5000 MΩ",min:5000,required:true},{sr:"6.3",label:"c) Bottom to earth:",type:"number",placeholder:"≥ 5000 MΩ",min:5000,required:true},{sr:"6.4",label:"d)Top to Bottom to Earth (CB Close)",type:"number",placeholder:"≥ 5000 MΩ",min:5000,required:true}]},
{sr:"7",label:"Insulation Resistance (with 2.5/ 5kv Megger) as per OEM (Megawin) Manual",type:"group",required:true,fields:[{sr:"7.1",label:"a) Top to bottom:",type:"number",placeholder:"≥ 300 MΩ",min:300,required:true},{sr:"7.2",label:"b) Top to earth:",type:"number",placeholder:"≥ 300 MΩ",min:300,required:true},{sr:"7.3",label:"c) Bottom to earth:",type:"number",placeholder:"≥ 300 MΩ",min:300,required:true},{sr:"7.4",label:"d)Top to Bottom to Earth (CB Close)",type:"number",placeholder:"≥ 300 MΩ",min:300,required:true}]},
{sr:"8",label:"Insulation Resistance (with 2.5/5kv Megger) as per OEM (Vans) Manual",type:"group",required:true,fields:[{sr:"8.1",label:"a) Top to bottom:",type:"number",placeholder:"≥ 100 MΩ",min:100,required:true},{sr:"8.2",label:"b) Top to earth:",type:"number",placeholder:"≥ 100 MΩ",min:100,required:true},{sr:"8.3",label:"c) Bottom to earth:",type:"number",placeholder:"≥ 100 MΩ",min:100,required:true},{sr:"8.4",label:"d)Top to Bottom to Earth (CB Close)",type:"number",placeholder:"≥ 100 MΩ",min:100,required:true}]},
{sr:"9",label:"Insulation Resistance/Resistance (with 500V Megger)",type:"group",required:true,fields:[{sr:"9.1",label:"a)Spring charging motor with earth",type:"number",placeholder:"≥ 2 MΩ",min:2,required:true},{sr:"9.2",label:"b)Closing coil resistance",type:"number",placeholder:"≥ 2 MΩ",min:2,required:true},{sr:"9.3",label:"c)Trip coil resistance",type:"number",placeholder:"≥ 2 MΩ",min:2,required:true},{sr:"9.4",label:"d)Spring charging  Time Of motor",type:"number",placeholder:"≤ 12 Sec.",max:12,required:true}]},
{sr:"10",label:"Contact resistance as per TI/MI/0054",type:"group",required:true,fields:[{sr:"10.1",label:"ALIND",type:"number",placeholder:"≤ 50 µΩ",max:50,required:true},{sr:"10.2",label:"Megawin",type:"number",placeholder:"≤ 100 µΩ",max:100,required:true},{sr:"10.3",label:"BHEL",type:"number",placeholder:"≤ 80 µΩ",max:80,required:true}]},
{sr:"11",label:"Operating time as per TI/MI/0054  / OEM",type:"group",required:true,fields:[]},
{sr:"12",label:"Alind Make",type:"group",required:true,fields:[{sr:"12.1",label:"a) Closing",type:"number",placeholder:"≤ 150 ms",max:150,required:true},{sr:"12.2",label:"b) Opening",type:"number",placeholder:"≤ 80 ms",max:80,required:true}]},
{sr:"13",label:"VANS Make as per OEM",type:"group",required:true,fields:[{sr:"13.1",label:"a) Closing",type:"number",placeholder:"≤ 80 ms",max:80,required:true},{sr:"13.2",label:"b) Opening",type:"number",placeholder:"≤ 65 ms",max:65,required:true}]},
{sr:"14",label:"Megawin Make",type:"group",required:true,fields:[{sr:"14.1",label:"a) Closing",type:"number",placeholder:"≤ 150 ms",max:150,required:true},{sr:"14.2",label:"b) Opening",type:"number",placeholder:"≤ 80 ms",max:80,required:true}]},
{sr:"15",label:"Key No.",type:"text",required:true},
{sr:"16",label:"Wipe (W1-W2) for Alind",type:"text",placeholder:"8+1/-0",required:true},
{sr:"17",label:"W1",type:"text",required:true},
{sr:"18",label:"W2",type:"text",required:true},
{sr:"19",label:"Travel (T1-T2) for Alind",type:"text",placeholder:"22±1",required:true},
{sr:"20",label:"T1",type:"text",required:true},
{sr:"21",label:"T2",type:"text",required:true},
{sr:"22",label:"Local/Remote operation",type:"text",required:true},
{sr:"23",label:"Duplicate earth and earth continuity",type:"text",required:true},
{sr:"24",label:"Terminal connection (check fortightness)",type:"textarea",placeholder:"OK / Not OK",multiline:true,required:true},
{sr:"25",label:"Check for",type:"textarea",multiline:true,required:true},
{sr:"26",label:"Mechanical tripping & closing",type:"text",required:true},
{sr:"27",label:"Heater circuit",type:"text",required:true},
{sr:"28",label:"Counter",type:"text",required:true},
{sr:"29",label:"Megger Used",type:"text",required:true},
{sr:"30",label:"a) Make",type:"text",required:true},
{sr:"31",label:"b) Serial No.",type:"text",required:true}
],
"25KV CT IR test":[
  {"sr":"0","label":"Name of the ","type":"dropdown","options":["TSS","SS","SSP"],"required":true},
{sr:"1",label:"Rly Identification No.",type:"text",placeholder:"text",required:true},
{sr:"2",label:"Make",type:"text",placeholder:"text",required:true},
{sr:"3",label:"Maker Sl.No",type:"text",placeholder:"text",required:true},
{sr:"4",label:"Manufacture's Year",type:"text",placeholder:"text",required:true},
{sr:"5",label:"Insulator( Check Condition)",type:"yesno",placeholder:"OK / Not OK",required:true},
{sr:"6",label:"Insulation resistance between (as per OEM)",type:"group",required:true,fields:
  [{sr:"6.1",label:"a) Pri to earth with 2.5kv Insulation Tester",type:"number",placeholder:"≥ 200 MΩ",min:200,required:true},
    {sr:"6.2",label:"b) Pri to sec with 2.5kv Insulation Tester",type:"number",placeholder:"≥ 200 MΩ",min:200,required:true},
    {sr:"6.3",label:"c) Sec to earth with 500v Insulation Tester",type:"number",placeholder:"≥ 2 MΩ",min:2,required:true}]},
{sr:"7",label:"Duplicate earth and earth continuity",type:"text",placeholder:"text",required:true}
],
"25KV NCT IR test":[
{sr:"1",label:"Rly Identification No.",type:"text",required:true},
{sr:"2",label:"Make",type:"text",required:true},
{sr:"3",label:"Maker Sl.No",type:"text",required:true},
{sr:"4",label:"Manufacture's Year",type:"text",required:true},
{sr:"5",label:"Insulator( Check Condition)",type:"text",required:true},
{sr:"6",label:"Insulation resistance between(as per OEM)",type:"group",required:true,fields:[{sr:"6.1",label:"a) Pri to earth with 2.5kv Insulation Tester",type:"number",placeholder:"≥ 200 MΩ",min:200,required:true},{sr:"6.2",label:"b) Pri to sec with 2.5kv Insulation Tester",type:"number",placeholder:"≥ 200 MΩ",min:200,required:true},{sr:"6.3",label:"c) Sec to earth with 500v Insulation Tester",type:"number",placeholder:"≥ 2 MΩ",min:2,required:true}]},
{sr:"7",label:"Tapping on primary",type:"text",required:true},
{sr:"8",label:"Ratio(by pri.injection)",type:"text",required:true},
{sr:"9",label:"Polarity(by DC flick test)",type:"text",required:true},
{sr:"10",label:"Duplicate earth and earth continuity",type:"text",required:true},
{sr:"11",label:"Terminal connector (check fortightness and general condition)",type:"textarea",placeholder:"OK / Not OK",multiline:true,required:true}
],
"120 KV LA":[
{"sr":"A","label":"Name of the ","type":"dropdown","options":["TSS","SS","SSP"],"required":true},
{sr:"1",label:"Rly Identification No.",type:"text",required:true},
{sr:"2",label:"Make",type:"text",required:true},
{sr:"3",label:"Type",type:"text",required:true},
{sr:"4",label:"Maker Sl.No",type:"text",required:true},
{sr:"5",label:"Manfacture's Year",type:"text",required:true},
{sr:"6",label:"Rating",type:"text",required:true},
{sr:"7",label:"External condition",type:"text",required:true},
{sr:"8",label:"Duplicate earth and earth continuity",type:"text",required:true},
{sr:"9",label:"Terminal connectors (check for tightness and general condition)",type:"textarea",placeholder:"OK / Not OK",multiline:true,required:true},
{sr:"10",label:"Insulation resistance with 5kv Insulation Tester (as per TI/MI/0041 )",type:"group",required:true,fields:[{sr:"10.1",label:"Top to Earth",type:"number",placeholder:"≥ 10 GΩ",min:10,required:true},{sr:"10.2",label:"Top to bottom",type:"number",placeholder:"≥ 10 GΩ",min:10,required:true}]},
{sr:"11",label:"Base insulator",type:"text",required:true},
{sr:"12",label:"Check Disconnector assembly",type:"text",required:true},
{sr:"13",label:"Size of flexible cable for disconnector",type:"text",placeholder:"35sqmm",required:true},
{sr:"14",label:"Check Surge monitor",type:"text",required:true},
{sr:"15",label:"Resistive Leakage current",type:"number",placeholder:"≤ 500 micro Amp",max:500,required:true},
{sr:"16",label:"Surge monitor serial no",type:"text",required:true},
{sr:"17",label:"Surge monitor counter reading",type:"text",required:true}
],
"25 KV DO FUSE ":[
{"sr":"0","label":"Name of the ","type":"dropdown","options":["TSS","SS","SSP"],"required":true},
{sr:"1",label:"Make",type:"text",required:true},
{sr:"2",label:"Maker Sl.No",type:"text",required:true},
{sr:"3",label:"Manufacter's Year",type:"text",required:true},
{sr:"4",label:"Insulator( Check Condition)",type:"text",required:true},
{sr:"5",label:"Insulation resistance between(with 2.5kv Insulation Tester)",type:"group",required:true,fields:[{sr:"5.1",label:"a)Male to Female (Open position)",type:"text",placeholder:"MΩ",required:true},{sr:"5.2",label:"b)Contact to Earth (Closed position)",type:"text",placeholder:"MΩ",required:true}]},
{sr:"6",label:"Duplicate earth and earth continuity",type:"text",required:true},
{sr:"7",label:"HV Side fuse link Provided",type:"text",required:true}
],
"25 KV SPI":[
{"sr":"A","label":"Name of the ","type":"dropdown","options":["TSS","SS","SSP"],"required":true},
{sr:"1",label:"Rly Identification No.",type:"text",required:true},
{sr:"2",label:"Make",type:"text",required:true},
{sr:"3",label:"Maker's serial No.",type:"text",required:true},
{sr:"4",label:"Rating",type:"text",placeholder:"25KV AMPS",required:true},
{sr:"5",label:"Manufacture's Year",type:"text",required:true},
{sr:"6",label:"Insulators ( check condition ).",type:"text",required:true},
{sr:"7",label:"Terminal connectors & connections",type:"text",required:true},
{sr:"8",label:"Contacts ( check for aligment & condition)",type:"textarea",placeholder:"OK / Not OK",multiline:true,required:true},
{sr:"9",label:"Operation ( manual )",type:"text",required:true},
{sr:"10",label:"Insulation resistance with 5KV Megger",type:"group",required:true,fields:[{sr:"10.1",label:"a) Pole to Pole (Open Position)",type:"number",placeholder:"≥ 200 MΩ",min:200,required:true},{sr:"10.2",label:"b) Pole to earth (Close Position)",type:"number",placeholder:"≥ 200 MΩ",min:200,required:true},{sr:"10.3",label:"Clearance between contact in open position",type:"number",placeholder:"≥ 500 mm",min:500,required:true}]},
{sr:"11",label:"Lock (check whether both lock and padlock fit conveniently when isolator is in open or close position)",type:"textarea",placeholder:"OK / Not OK",multiline:true,required:true},
{sr:"12",label:"Duplicate earth and earth continuity",type:"text",required:true},
{sr:"13",label:"Megger Used",type:"text",required:true},
{sr:"14",label:"Make",type:"text",required:true},
{sr:"15",label:"Serial No.",type:"text",required:true}
],
"25 KV DPI":[
{"sr":"A","label":"Name of the ","type":"dropdown","options":["TSS","SS","SSP"],"required":true},
{sr:"1",label:"Rly Identification No.",type:"text",required:true},
{sr:"2",label:"Make",type:"text",required:true},
{sr:"3",label:"Maker's serial No.",type:"text",required:true},
{sr:"4",label:"Rating",type:"text",required:true},
{sr:"5",label:"Manufacture's Year",type:"text",required:true},
{sr:"6",label:"Insulators Condition",type:"text",required:true},
{sr:"7",label:"Terminal connectors",type:"text",required:true},
{sr:"8",label:"Contacts ( check for",type:"text",placeholder:"aligment & condition)",required:true},
{sr:"9",label:"Operation ( manual )",type:"text",required:true},
{sr:"10",label:"Insulation resistance with 5KV Megger.",type:"group",required:true,fields:[{sr:"10.1",label:"a) Pole to pole (Open Position)",type:"number",placeholder:"≥ 200 MΩ",min:200,required:true},{sr:"10.2",label:"b) Pole to Earth (Close Position)",type:"number",placeholder:"≥ 200 MΩ",min:200,required:true},{sr:"10.3",label:"c) Pole A to Pole B(Close position)",type:"number",placeholder:"≥ 200 MΩ",min:200,required:true}]},
{sr:"11",label:"Clearance between contact in open position",type:"number",placeholder:"≥ 500 mm",min:500,required:true},
{sr:"12",label:"Lock (check whether both lock and padlock fit conveniently when isolator is in open or close position)",type:"textarea",placeholder:"OK / Not OK",multiline:true,required:true},
{sr:"13",label:"Duplicate earth and earth continuity",type:"text",required:true},
{sr:"14",label:"Terminal connections",type:"text",required:true}
],
"132KV SF6 CB":[
{sr:"1",label:"Identification No.",type:"text",required:true},
{sr:"2",label:"Make",type:"text",required:true},
{sr:"3",label:"Maker Sl.No",type:"text",required:true},
{sr:"4",label:"Manufacture's Year",type:"text",required:true},
{sr:"5",label:"External condition (check porcelain carefully)",type:"text",required:true},
{sr:"6",label:"Insulation Resistance  with 5kv Megger as per OEM- CGL Manual.",type:"group",required:true,fields:
  [{sr:"6.1",label:"a) Top to bottom",type:"number",placeholder:"≥ 1500 MΩ",min:1500,required:true},
    {"sr":"6","label":"Ratio Test","type":"multi","count":2,"labels":["Pri Voltage","Main Voltage"],unit:"MQ",min:100,max:10,required:true},    
    {sr:"6.2",label:"b) Top to earth",type:"number",placeholder:"≥ 1500 MΩ",min:1500,required:true},
    {sr:"6.3",label:"c) Bottom to earth",type:"number",placeholder:"≥ 1500 MΩ",min:1500,required:true},
    {sr:"6.4",label:"d)Top to Bottom to Earth (CB Close)",type:"number",placeholder:"≥ 1500 MΩ",min:1500,required:true}]},
{sr:"7",label:"Breaker operating time as per OEM- CGL manual",type:"text",required:true},
{sr:"8",label:"CGL Make",type:"group",required:true,fields:[{sr:"8.1",label:"Close (ms)",type:"number",placeholder:"≤ 130",max:130,required:true},{sr:"8.2",label:"Open (ms)",type:"number",placeholder:"≤ 30",max:30,required:true},{sr:"8.3",label:"Contact resistance ( µ Ω)",type:"text",placeholder:"50",required:true}]},
{sr:"9",label:"ABB Make",type:"group",required:true,fields:[{sr:"9.1",label:"Close (ms)",type:"number",placeholder:"≤ 75 ms",max:75,required:true},{sr:"9.2",label:"Open (ms)",type:"number",placeholder:"≤ 45 ms",max:45,required:true},{sr:"9.3",label:"Contact resistance ( µ Ω)",type:"text",placeholder:"42",required:true}]},
{sr:"10",label:"Local/Remote operation",type:"text",required:true},
{sr:"11",label:"Duplicate earth and earth continuity",type:"text",required:true},
{sr:"12",label:"Terminal connection (check for tightness and general condition)",type:"textarea",placeholder:"OK / Not OK",multiline:true,required:true},
{sr:"13",label:"Check for",type:"textarea",multiline:true,required:true},
{sr:"14",label:"Mechanical tripping & closing",type:"text",required:true},
{sr:"15",label:"Heater circuit",type:"text",required:true},
{sr:"16",label:"DC fail test (condensor tripping)",type:"text",required:true},
{sr:"17",label:"Counter",type:"text",required:true},
{sr:"18",label:"Interlocking CB with associated Isolator",type:"text",required:true},
{sr:"19",label:"SF6 gas pressure  (CGL &ABB)",type:"text",placeholder:"6.5 kg/cm²",required:true},
{sr:"20",label:"Alarm at 6.5 kg/cm²",type:"text",required:true},
{sr:"21",label:"Lock out at 6.0",type:"text",placeholder:"kg/cm²",required:true},
{sr:"22",label:"Gas Leakage test",type:"text",required:true},
{sr:"23",label:"Healthiness of heaters in housing",type:"text",required:true}
],
"25KV AT":[
  {"sr":"A","label":"Name of the ","type":"dropdown","options":["TSS","SS","SSP"],"required":true},
{sr:"1",label:"Identification No.",type:"text",required:true},
{sr:"2",label:"Make",type:"text",required:true},
{sr:"3",label:"Maker Sl.No",type:"text",required:true},
{sr:"4",label:"Manufacter's Year",type:"text",required:true},
{sr:"5",label:"Rating",type:"text",required:true},
{sr:"6",label:"Insulator( Check Condition)",type:"text",required:true},
{sr:"7",label:"Insulation resistance between(as per OEM)",type:"group",required:true,fields:
  [{sr:"7.1",label:"a) Pri to sec with 2.5kv Insulation Tester",type:"number",placeholder:"≥ 200 MΩ",min:200,required:true},
    {sr:"7.2",label:"b) Pri to earth with 2.5kv Insulation Tester",type:"number",placeholder:"≥ 200 MΩ",min:200,required:true},
    {sr:"7.3",label:"c) Sec to earth with 500v Insulation Tester",type:"number",placeholder:"≥ 2 MΩ",min:2,required:true}]},
{sr:"8",label:"Duplicate earth and earth continuity",type:"text",required:true},
{sr:"9",label:"Earthing tightness and general condition)",type:"text",required:true},
{sr:"10",label:"No of Tapping on secondary side",type:"text",required:true},
{sr:"11",label:"Ratio test",type:"group",required:true,fields:
  [{"sr":"11.1","label":"Ratio test(For T1","type":"triplet","parts":["Applied Voltage in Pri.","Measured Voltage in Sec.","Calculated Voltage (V) 	"],"unit":"%","min":0,"max":100,"required":true},
    {"sr":"11.2","label":"Ratio test(For T2","type":"triplet","parts":["Applied Voltage in Pri.","Measured Voltage in Sec.","Calculated Voltage (V) 	"],"unit":"%","min":0,"max":100,"required":true},
    {"sr":"11.3","label":"Ratio test(For T3","type":"triplet","parts":["Applied Voltage in Pri.","Measured Voltage in Sec.","Calculated Voltage (V) 	"],"unit":"%","min":0,"max":100,"required":true},
    {"sr":"11.4","label":"Ratio test(For T4","type":"triplet","parts":["Applied Voltage in Pri.","Measured Voltage in Sec.","Calculated Voltage (V) 	"],"unit":"%","min":0,"max":100,"required":true}],},
{sr:"12",label:"Oil level",type:"text",required:true},
{sr:"13",label:"HV Side Fuse Link Provided",type:"text",required:true},
{sr:"14",label:"LV Side Neutral Grounded",type:"text",required:true},
{sr:"15",label:"BDV of Transformer oil",type:"number",placeholder:"≥ 40 KV",min:40,required:true},
{sr:"16",label:"Arcing horn gap",type:"text",required:true},
{sr:"17",label:"Earth resistance  value",type:"number",placeholder:"≤ 10 Ohm",max:10,required:true}
],
"132KV DPI":[
{sr:"1",label:"Identification No.",type:"text",required:true},
{sr:"2",label:"Make",type:"text",required:true},
{sr:"3",label:"Maker's serial No.",type:"text",required:true},
{sr:"4",label:"Manufacture's Year",type:"text",required:true},
{sr:"5",label:"Insulators",type:"text",required:false},
{sr:"6",label:"( check condition )",type:"multi",placeholder:"Applied Voltage in Primary",count:2,labels:["A Pole","B Pole"],required:true},
{sr:"8",label:"Terminal connectors	",type:"multi",placeholder:"Applied Voltage in Primary",count:2,labels:["A Pole","B Pole"],required:true},
{sr:"9",label:"Contacts ( check for aligment & condition)		",type:"multi",placeholder:"Applied Voltage in Primary",count:2,labels:["A Pole","B Pole"],required:true},
{sr:"10",label:"Operation ( manual )		",type:"multi",placeholder:"Applied Voltage in Primary",count:2,labels:["A Pole","B Pole"],required:true},
{sr:"11",label:"Insulation resistance between terminal & Earth with 5KV Megger		",type:"multi",placeholder:"Applied Voltage in Primary",count:2,labels:["A Pole","B Pole"],required:true},
{sr:"12",label:"Contacts Resistance		",type:"multi",placeholder:"Applied Voltage in Primary",count:2,labels:["A Pole","B Pole"],required:true},
{sr:"13",label:"Lock (check whether both lock and padlock fit is in open or close position",type:"multi",placeholder:"Applied Voltage in Primary",count:2,labels:["A Pole","B Pole"],required:true},
{sr:"14",label:"Providing Duplicate earth",type:"multi",placeholder:"Applied Voltage in Primary",count:2,labels:["A Pole","B Pole"],required:true},
{sr:"15",label:"Earthing Continuity",type:"multi",placeholder:"Applied Voltage in Primary",count:2,labels:["A Pole","B Pole"],required:true},
{sr:"16",label:"Checking of Terminal connections",type:"multi",placeholder:"Applied Voltage in Primary",count:2,labels:["A Pole","B Pole"],required:true}
],
"132KV CT-IR":[
{sr:"1",label:"Rly Identification No.",type:"text",required:true},
{sr:"2",label:"Make",type:"text",required:true},
{sr:"3",label:"Maker Sl.No",type:"text",required:true},
{sr:"4",label:"Manufacture's Year",type:"text",required:true},
{sr:"5",label:"Insulator( Check Condition)",type:"text",required:true},
{sr:"6",label:"Insulation resistance between(as per OEM)",type:"group",required:true,fields:
  [{sr:"6.1",label:"a) Pri to sec with 5kv Insulation Tester",type:"number",placeholder:"≥ 2000 MΩ",min:2000,required:true},
    {sr:"6.2",label:"b) Pri to earth with 5kv Insulation Tester",type:"number",placeholder:"≥ 2000 MΩ",min:2000,required:true},
    {sr:"6.3",label:"c) Sec to earth with 500v Insulation Tester",type:"number",placeholder:"≥ 200 MΩ",min:200,required:true}]},
{sr:"7",label:"Polarity(by DC flick test)",type:"text",required:true},
{sr:"8",label:"Oil level",type:"text",required:true},
{sr:"9",label:"Duplicate earth and earth continuity",type:"text",required:true},
{sr:"10",label:"Terminal connector (check for tightness and general condition)",type:"textarea",placeholder:"OK / Not OK",multiline:true,required:true}
],
"132kv PT" : [
{sr:"1",label:"Rly Identification No.",type:"text",required:true},
{sr:"2",label:"Make",type:"text",required:true},
{sr:"3",label:"Maker Sl.No",type:"text",required:true},
{sr:"4",label:"Manufacter's Year",type:"text",required:true},
{sr:"5",label:"Insulator( Check Condition)",type:"text",required:true},
{sr:"6",label:"Insulation resistance between(as per OEM)",type:"group",required:true,fields:
  [{sr:"6.1",label:"a) Pri to sec with 2.5kv Insulation Tester:",type:"number",placeholder:"≥ 2000 MΩ",min:2000,required:true},
    {sr:"6.2",label:"b) Pri to earth with 2.5kv Insulation Tester",type:"number",placeholder:"≥ 2000 MΩ",min:2000,required:true},
    {sr:"6.3",label:"c) Sec to earth with 500v Insulation Tester:",type:"number",placeholder:"≥ 200 MΩ",min:200,required:true}]},
{sr:"7",label:"Secondary continuity",type:"text",required:true},
{sr:"8",label:"Duplicate earth and earth continuity",type:"text",required:true},
{sr:"9",label:"Terminal connector (check for tightness and general condition)",type:"textarea",placeholder:"OK / Not OK",multiline:true,required:true},
{sr:"9.1",label:"Ratio test",type:"group",required:true,fields:
  [{"sr":"9.1","label":"Ratio Test","type":"multi","count":2,"labels":["Pri Voltage","Main Voltage"],"required":true},
    {sr:"9.2",label:"Applied Voltage (v)","type":"multi","count":2,"labels":["Pri Voltage","Main Voltage"],"required":true},
    {sr:"9.3",label:"Applied Voltage (v)","type":"multi","count":2,"labels":["Pri Voltage","Main Voltage"],"required":true}]},
{sr:"2",label:"Oil level",type:"text",required:true},
{sr:"3",label:"Check primary earth continuity",type:"text",required:true}
],
"Earth Resistance test":[
{"sr":"A","label":"Name of the ","type":"dropdown","options":["TSS","SS","SSP"],"required":true},
{sr:"1",label:"EP-01",type:"text",placeholder:"Ω","min":0,"max":100,"required":true},
{sr:"2",label:"EP-02",type:"text",placeholder:"Ω",required:true},
{sr:"3",label:"EP-03",type:"text",placeholder:"Ω",required:true},
{sr:"4",label:"EP-04",type:"text",placeholder:"Ω",required:true},
{sr:"5",label:"EP-05",type:"text",placeholder:"Ω",required:true},
{sr:"6",label:"EP-06",type:"text",placeholder:"Ω",required:true},
{sr:"7",label:"EP-07",type:"text",placeholder:"Ω",required:true},
{sr:"8",label:"EP-08",type:"text",placeholder:"Ω",required:true},
{sr:"9",label:"EP-09",type:"text",placeholder:"Ω",required:true},
{sr:"10",label:"EP-10",type:"text",placeholder:"Ω",required:true},
{sr:"11",label:"EP-11",type:"text",placeholder:"Ω",required:true},
{sr:"12",label:"EP-12",type:"text",placeholder:"Ω",required:true},
{sr:"13",label:"EP-13",type:"text",placeholder:"Ω",required:true},
{sr:"14",label:"EP-14",type:"text",placeholder:"Ω",required:true},
{sr:"15",label:"EP-15",type:"text",placeholder:"Ω",required:true},
{sr:"16",label:"EP-16",type:"text",placeholder:"Ω",required:true},
{sr:"17",label:"EP-17",type:"text",placeholder:"Ω",required:true},
{sr:"18",label:"EP-18",type:"text",placeholder:"Ω",required:true},
{sr:"19",label:"EP-19",type:"text",placeholder:"Ω",required:true},
{sr:"20",label:"EP-20",type:"text",placeholder:"Ω",required:true},
{sr:"21",label:"EP-21",type:"text",placeholder:"Ω",required:true},
{sr:"22",label:"EP-22",type:"text",placeholder:"Ω",required:true},
{sr:"23",label:"EP-23",type:"text",placeholder:"Ω",required:true},
{sr:"24",label:"EP-24",type:"text",placeholder:"Ω",required:true},
{sr:"25",label:"EP-25",type:"text",placeholder:"Ω",required:true},
{sr:"26",label:"EP-26",type:"text",placeholder:"Ω",required:true},
{sr:"27",label:"EP-27",type:"text",placeholder:"Ω",required:true},
{sr:"28",label:"EP-28",type:"text",placeholder:"Ω",required:true},
{sr:"29",label:"EP-29",type:"text",placeholder:"Ω",required:true},
{sr:"30",label:"EP-30",type:"text",placeholder:"Ω",required:true},
{sr:"31",label:"EP-31",type:"text",placeholder:"Ω",required:true},
{sr:"32",label:"EP-32",type:"text",placeholder:"Ω",required:true},
{sr:"33",label:"EP-33",type:"text",placeholder:"Ω",required:true},
{sr:"34",label:"EP-34",type:"text",placeholder:"Ω",required:true},
{sr:"35",label:"EP-35",type:"text",placeholder:"Ω",required:true},
{sr:"36",label:"EP-36",type:"text",placeholder:"Ω",required:true},
{sr:"37",label:"EP-37",type:"text",placeholder:"Ω",required:true},
{sr:"38",label:"EP-38",type:"text",placeholder:"Ω",required:true},
{sr:"39",label:"EP-39",type:"text",placeholder:"Ω",required:true},
{sr:"40",label:"EP-40",type:"text",placeholder:"Ω",required:true}
],
"AC DB":[
{"sr":"A","label":"Name of the ","type":"dropdown","options":["TSS","SS","SSP"],"required":true},
{sr:"1",label:"Operation of main switches",type:"text",required:true},
{sr:"2",label:"Check whether proper fuse is put in",type:"text",required:true},
{sr:"3",label:"phase line, also check rating & continuity",type:"text",required:true},
{sr:"4",label:"Incomming Double pole switch",type:"text",required:true},
{sr:"5",label:"Insulation resistance with 500V Insulation Tester switch incomming,  outgoing & other switches in off position",type:"group",required:true,fields:
  [{sr:"5.1",label:"a) Between phase & Neutral",type:"text",placeholder:"MΩ",required:true},
    {sr:"5.2",label:"b)  Between phase & Earth",type:"text",placeholder:"MΩ",required:true}]},
{sr:"6",label:"Operation of Changeover Switch",type:"text",required:true},
{sr:"7",label:"Earth connection",type:"text",required:true}
],
"DC DB":[
{"sr":"A","label":"Name of the ","type":"dropdown","options":["TSS","SS","SSP"],"required":true},
{sr:"1",label:"Miniature Circuit Breaker",type:"text",required:true},
{sr:"2",label:"Check operation)",type:"text",required:true},
{sr:"3",label:"Fuse (Check rating & Continuity)",type:"text",required:true},
{sr:"4",label:"Make",type:"text",required:true},
{sr:"5",label:"Insulation resistance with 500V Insulation Tester (With M.C.B. open)",type:"group",required:true,fields:[{sr:"5.1",label:"a) Positive to earth",type:"text",placeholder:"MΩ",required:true},{sr:"5.2",label:"b) Negative to Earth",type:"text",placeholder:"MΩ",required:true},{sr:"5.3",label:"c) Positive to Negative",type:"text",placeholder:"MΩ",required:true}]},
{sr:"6",label:"Voltmeter & Indication Lamp",type:"text",required:true},
{sr:"7",label:"Earthing ( Check for duplicate earth &",type:"textarea",multiline:true,required:true},
{sr:"8",label:"earth continuity)",type:"text",required:true}
],
"CLEARANCE" : [
{sr:"1",label:"Height of live conductor above Ground level",type:"group",required:true,fields:[{sr:"1.1",label:"i)132KV (Min 4.6 m)",type:"text",required:true},{sr:"1.2",label:"ii) 25kV (Min 3.8 m)",type:"text",required:true}]},
{sr:"2",label:"Clearance between two live phase",type:"group",required:true,fields:[{sr:"2.1",label:"i)132KV (Min 1.3 m)",type:"text",required:true},{sr:"2.2",label:"ii) 25kV (Min 0.6 m )",type:"text",required:true}]},
{sr:"3",label:"Electrical clearance between live and earthed parts",type:"group",required:true,fields:[{sr:"3.1",label:"i)132KV (Min 1.3 m)",type:"text",required:true},{sr:"3.2",label:"ii) 25kV (Min 0.5 m )",type:"text",required:true}]},
{sr:"4",label:"Visual inspection of insulators",type:"text",required:true},
{sr:"5",label:"Number plates",type:"text",required:true},
{sr:"6",label:"Fencing earthing",type:"text",required:true}
]
};
window.FORM_CONFIG = FORM_CONFIG;